// Translate only presentation text. Stored CRM values and customer-facing messages remain unchanged.
const labels: Record<string, string> = {
  "Provider response unavailable; reconcile before retry": "Ответ сервиса отправки недоступен. Проверьте статус перед повторной попыткой.",
  "Restaurant anrufen": "Позвонить в заведение",
  "WhatsApp schreiben": "Написать в WhatsApp",
  "Für die erste Version als geordnete Liste mit Navigation und Besuchsstatus.": "Остановки маршрута показаны списком с навигацией и статусом визита.",
  "Latitude": "Широта",
  "Longitude": "Долгота",
  "Navigation": "Маршрут",
  "Webseite öffnen": "Открыть сайт",
  "Angebot wurde gespeichert und als gesendet markiert.": "Предложение сохранено и отмечено как отправленное.",
  "Restaurant aktualisiert.": "Карточка заведения обновлена.",
  "Restaurant wurde archiviert.": "Заведение перемещено в архив.",
  "WhatsApp-Nachricht wurde als gesendet bestätigt.": "Отправка сообщения WhatsApp подтверждена.",
  "Angebot konnte nicht aktualisiert werden.": "Не удалось обновить предложение.",
  "Angebot konnte nicht geladen werden.": "Не удалось загрузить предложение.",
  "Demo konnte nicht geladen werden.": "Не удалось загрузить демо.",
  "Demo wurde veröffentlicht, aber Restaurant konnte nicht aktualisiert werden.": "Демо опубликовано, но карточку заведения не удалось обновить.",
  "E-Mail versandt; CRM-Speicherung fehlgeschlagen. Nicht erneut senden.": "Письмо отправлено, но не записано в CRM. Не отправляйте повторно.",
  "E-Mail-Versand und Antwortempfang sind noch nicht konfiguriert.": "Отправка писем и получение ответов ещё не настроены.",
  "Kein passendes Restaurant gefunden.": "Подходящее заведение не найдено.",
  "Kein Sales-Zugriff.": "Нет доступа к Sales.",
  "Nachweis der vorherigen ausdrücklichen Einwilligung fehlt (Quelle, Datum, Umfang).": "Нужно указать подтверждение предварительного согласия: источник, дату и объём.",
  "Nicht angemeldet.": "Вы не вошли в систему.",
  "Nur Admins dürfen versenden.": "Отправлять письма может только администратор.",
  "PDF konnte nicht gespeichert werden.": "Не удалось сохранить PDF.",
  "Provider hat den Versand nicht bestätigt. Bitte prüfen.": "Сервис отправки не подтвердил письмо. Проверьте статус.",
  "Restaurant fehlt.": "Заведение не указано.",
  "Restaurant konnte nicht geladen werden.": "Не удалось загрузить заведение.",
  "Restaurant nicht gefunden.": "Заведение не найдено.",
  "Restaurant oder E-Mail fehlt.": "Не указано заведение или его электронная почта.",
  "Restaurantname fehlt.": "Не указано название заведения.",
  "Supabase fehlt.": "Supabase недоступен.",
  "Supabase ist nicht konfiguriert.": "Supabase не настроен.",
  "Theme konnte nicht gespeichert werden.": "Не удалось сохранить тему оформления.",
  "Ungültige Demo oder Theme.": "Недопустимое демо или тема оформления.",
  "Ungültige ID.": "Недопустимый идентификатор.",
  "Versandstatus unklar. Kein erneuter automatischer Versand.": "Статус отправки неясен. Повторной автоматической отправки не будет.",
  "after_visit": "После визита",
  "CSV Import": "Импорт CSV",
  "email": "Электронная почта",
  "Follow-up": "Повторный контакт",
  "internal": "Внутреннее сообщение",
  "Kanal": "Канал",
  "Name": "Название",
  "PDF erstellt": "PDF создан",
  "sms": "SMS",
  "whatsapp": "WhatsApp",
  "Abbrechen": "Отмена",
  "Anruf": "Звонок",
  "Aufgabe": "Задача",
  "Demo konnte nicht veröffentlicht werden.": "Не удалось опубликовать демо.",
  "E-Mail": "Электронная почта",
  "Keine Adresse": "Адрес не указан",
  "Keine Telefonnummer": "Телефон не указан",
  "Keine offenen Aufgaben.": "Открытых задач нет.",
  "PDF noch nicht erstellt": "PDF ещё не создан",
  "Restaurant konnte nicht gespeichert werden.": "Не удалось сохранить заведение.",
  "Zurück": "Назад",
  "Abgelehnt": "Отказ",
  "Abgelaufen": "Истёк срок",
  "Abgeschlossen": "Завершено",
  "Alle Restaurants": "Все заведения",
  "Aktuelle Kennzahlen, Conversion und offene Potenziale.": "Текущие показатели, конверсия и возможности для роста.",
  "Aktuellen Standort verwenden": "Использовать текущее местоположение",
  "Adresse": "Адрес",
  "Angebot": "Предложение",
  "Angebotsdatum": "Дата предложения",
  "Ansprechpartner": "Контактное лицо",
  "Anzahl Bewertungen": "Количество отзывов",
  "Angenommen": "Принято",
  "Angebot erstellen": "Создать предложение",
  "Angebot gesendet": "Предложение отправлено",
  "Angebot senden": "Отправить предложение",
  "Angebote angenommen": "Принятые предложения",
  "Angebote gesendet": "Отправленные предложения",
  "Anrufen": "Позвонить",
  "Aufgaben": "Задачи",
  "Automatisch auswählen": "Выбрать автоматически",
  "Automatisches Demo": "Автоматическое демо",
  "Betreff": "Тема",
  "Bilder": "Изображения",
  "Bäckerei": "Пекарня",
  "Bar": "Бар",
  "Besuch geplant": "Визит запланирован",
  "Besucht": "Посещено",
  "Café": "Кафе",
  "Dashboard": "Обзор",
  "Daten": "Данные",
  "Daten aktualisieren.": "Обновите сведения о заведении.",
  "Datum": "Дата",
  "Demo aktualisieren": "Обновить демо",
  "Demo veröffentlichen": "Опубликовать демо",
  "Demo gesendet": "Демо отправлено",
  "Demo per WhatsApp senden": "Отправить демо в WhatsApp",
  "Durchgeführte Besuche": "Проведённые визиты",
  "Einfacher Import mit Vorschau. Die Struktur kann später für Supabase erweitert werden.": "Импорт с предварительной проверкой данных.",
  "Einmalige Erstellungskosten": "Стоимость создания",
  "E-Mail senden": "Отправить письмо",
  "Einmalige Verkäufe": "Разовые продажи",
  "Entwurf": "Черновик",
  "Ergebnis": "Результат",
  "Ergebnis speichern und nächsten Kontakt planen.": "Сохраните результат и запланируйте следующий контакт.",
  "Export, Import und anpassbare Paketvorlagen.": "Экспорт, импорт и шаблоны пакетов услуг.",
  "Erneut besuchen": "Посетить повторно",
  "expired": "Истёк срок",
  "first_contact": "Первый контакт",
  "follow_up": "Повторный контакт",
  "generated": "PDF создан",
  "Geplant": "Запланировано",
  "Geplanter Besuch": "Запланированный визит",
  "Gespräch geführt mit": "С кем говорили",
  "Gesendet": "Отправлено",
  "Geschäftsführer": "Управляющий",
  "Grill": "Гриль",
  "Heute geplant": "На сегодня",
  "Google Maps Link": "Ссылка Google Maps",
  "Google Rating": "Оценка Google",
  "Gültig bis": "Действительно до",
  "Hausnummer": "Номер дома",
  "Imbiss": "Закусочная",
  "Inhaber": "Владелец",
  "Interesse vorhanden": "Есть интерес",
  "Interesse": "Интерес",
  "Interessiert": "Заинтересован",
  "Kein Interesse": "Нет интереса",
  "Kunde gewonnen": "Клиент привлечён",
  "Kunden gewonnen": "Привлечено клиентов",
  "Kategorie": "Категория",
  "Kompakte Übersicht über Besuche, Rückrufe und offene Kontakte.": "Визиты, звонки и контакты, требующие внимания.",
  "Lieferdienst": "Доставка",
  "Mehr": "Ещё",
  "Monatliche Kosten": "Ежемесячная стоимость",
  "Mitarbeiter": "Сотрудник",
  "Monatliche Verträge": "Ежемесячные договоры",
  "Neu": "Новый",
  "Neue Restaurants": "Новые заведения",
  "Neues Restaurant": "Новое заведение",
  "Neuer Termin vereinbart": "Назначена новая встреча",
  "Niemand erreicht": "Не удалось связаться",
  "Nicht erreicht": "Не удалось связаться",
  "Noch kein Demo ausgewählt": "Демо пока не выбрано",
  "Noch kein Kontaktverlauf.": "История общения пока пуста.",
  "Noch keine aktiven Vorlagen vorhanden.": "Активных шаблонов пока нет.",
  "Noch keine Fotos vorhanden.": "Фотографий пока нет.",
  "Noch keine Restaurants gefunden.": "Заведения не найдены.",
  "Noch keine Stopps geplant.": "Остановок пока нет.",
  "Noch nicht ausgewählt": "Пока не выбрано",
  "Nur nach Bestätigung wird der Versand im Kontaktverlauf gespeichert.": "Отправка появится в истории только после подтверждения.",
  "Ohne Namen": "Без названия",
  "Ort": "Город",
  "Paket": "Пакет услуг",
  "Paketname": "Название пакета",
  "Pipeline": "Воронка продаж",
  "PLZ": "Индекс",
  "Position des Ansprechpartners": "Должность контактного лица",
  "Preis": "Цена",
  "Pizzeria": "Пиццерия",
  "Potenzial monatlich": "Потенциал за месяц",
  "Restaurant": "Ресторан",
  "Restaurant bearbeiten": "Изменить заведение",
  "Restaurant hinzufügen.": "Добавьте новое заведение.",
  "Restaurantname": "Название заведения",
  "Restaurantname *": "Название заведения *",
  "Restaurants": "Заведения",
  "Restaurants nach aktuellem Status verschieben und Fortschritt sichtbar machen.": "Перемещайте заведения между этапами и отслеживайте продвижение.",
  "Rückruf": "Перезвонить",
  "Rückruf notwendig": "Нужно перезвонить",
  "Sonstige Person": "Другое лицо",
  "Sonstiges": "Другое",
  "Sonderwünsche": "Особые пожелания",
  "Suchen, filtern und direkt in die Restaurantkarte springen.": "Ищите и фильтруйте заведения, открывайте их карточки.",
  "Status": "Статус",
  "Straße": "Улица",
  "Später erneut kontaktieren": "Связаться позже",
  "Tour": "Маршрут",
  "Tour planen": "Планировать маршрут",
  "Typ": "Тип",
  "Überfällige Aufgaben, heutige Kontakte und die nächsten sieben Tage.": "Просроченные задачи, контакты на сегодня и следующие семь дней.",
  "Überfällige Aufgaben": "Просроченные задачи",
  "Uhrzeit": "Время",
  "Verantwortlich": "Ответственный",
  "Veröffentlichen": "Опубликовать",
  "Vom Restaurant Scout Bot gefundene Leads und Runs.": "Лиды и запуски Restaurant Scout Bot.",
  "Webseite": "Сайт",
  "Wiederherstellen": "Восстановить",
  "visit": "Визит",
  "WhatsApp gesendet": "WhatsApp отправлен",
  "appointment": "Встреча",
  "custom": "Другое",
  "demo": "Демо",
  "draft": "Черновик",
  "offer": "Предложение",
  "rejection": "Отказ",
  "reminder": "Напоминание",
  "sent": "Отправлено",
  "accepted": "Принято",
  "agent_discovery": "Найдено ботом",
  "completed": "Завершено",
  "converted": "Конвертирован",
  "done": "Выполнено",
  "duplicate": "Дубликат",
  "failed": "Ошибка",
  "missing": "Сайта нет",
  "new": "Новый",
  "none": "Нет",
  "ok": "Сайт работает",
  "planned": "Запланировано",
  "qualified": "Подходит",
  "running": "Выполняется",
  "skipped": "Пропущено",
  "to_plan": "Запланировать",
  "unknown": "Неизвестно",
  "rejected": "Отклонено"
};

export function salesUiLabel(value: string): string {
  return labels[value] || value;
}

export function salesUiNote(value: string): string {
  return value.split("\n").map((line) => {
    if (line.startsWith("Gespräch geführt mit: ")) {
      return `С кем говорили: ${salesUiLabel(line.slice(22).replace(/\.$/, ""))}.`;
    }
    if (line.startsWith("Ergebnis: ")) {
      return `Результат: ${salesUiLabel(line.slice(10).replace(/\.$/, ""))}.`;
    }
    if (line.startsWith("Aufgabe erstellt: ")) {
      return `Задача создана: ${salesUiLabel(line.slice(18).replace(/\.$/, ""))}.`;
    }
    const pipeline = /^Status in Pipeline geändert: (.+) → (.+)\.$/.exec(line);
    if (pipeline) {
      return `Этап воронки изменён: ${salesUiLabel(pipeline[1])} → ${salesUiLabel(pipeline[2])}.`;
    }
    return salesUiLabel(line);
  }).join("\n");
}
